language: ruby
os:
- osx
branches:
  only:
  - master
install:
- brew update
- brew --version
- brew install zsh
- zsh --version
- git clone --depth 1 https://github.com/robbyrussell/oh-my-zsh.git test/oh-my-zsh
- cd test/oh-my-zsh && git rev-parse HEAD
script:
- ZDOTDIR=$PWD/test ZSH=$PWD/test/oh-my-zsh zsh -cli 'exit 0'
notifications:
  slack:
    secure: OMjzJiTZh5AnOodlEEqpzEOwAUerMQgoYbGTsK6dv2z+tlhR1rOT5XGWLYC0Dmc+zbbfSFJuv1msGDQvMTB0YbYeOurHpPt55B5pyQyUoL8GoV4HwDIBaRBsxKdGkuQhz2q1J/jPBDL3HA/lfrvEsvN1P2zilW/h/bKIkIuMZMSmt+6ppPWCERac8/KnctdcGWtQeZlOCItzlmbjka6w1doSKXvN4mRGmKw2n0Q5+fNBG2ZfzBx4yUkZM0UbvJlG3UVJ7pG8V/gDRGJo58KXiukgurfwh8h+2/wekvTo0Xgu5jg6FV5Kt7pZdqL6D1GFtUGVhzLMy/gEtCSSnv45r2DU/aELyR1F4rWWKjyn4oOnjJ92XF/uaeRuN0woOgG600EToogZujuna48xnskK8SM6ZGIP1nGaWMZUhI4g8ajTkYLf1wA1Ro8iXkdtKbdlegn3lo7cD+MYG4anezSRs024RzDE3B+WeoUUTo3uzQ+WDPKX+Z+D2eH8aGYzh4ixBH5wGjSbE+S3ltLFT3jbOx8DaLcOWMNEh/m1pXg6tsYHlm4MPDYTx6JRYZZF/fZ3cHs8rqIx5kinEUsvNzz3LUjD7OZyEVnuOd1BgCq52n7AIYwG9pWQ7/72yBVLdJ9mYT9on0NugiryVdRUFKZkF0vh/4HlrQOuUfEihxB4W6o=
